### ISSUE TITLE
IR2Native Model?

### ISSUE THREAD

**Issue by mostafaelhoushi** [google/ml-compiler-opt#1]
Thanks for opensourcing the code!
I would like to ask, does the repo contain the code for the IR2Native supervised model that estimates the function size of a caller?

By skimming through the files in the repo, it seems that it only contains the RL model.

**Comment by mtrofin** [comment]
Sorry for the delay in replying.

The code extracting the data for IR2Native would have been in llvm - it's essentially just extracting the features used llvm/lib/Analysis/InlineSizeEstimatorAnalysis.cpp, right after inlining (since then the function's body is all that's necessary to predict its final size - i.e. you don't need to look at other functions), and then the size expression during AsmPrint - ing, and dumping them out. 

We're not using it anymore though - the current training algorithms use final size instead (at a point, we should probably yank out InlineSizeEstimatorAnalysis, too)

If you're interested in size estimation with supervised learning, please add it to the agenda for the next [LLVM MLGO meeting](https://docs.google.com/document/d/1JecbplF09l3swTjze-UVeLh4L48svJxGVy4mz_e9Rhs/edit#heading=h.265ejd9hk1mc) - I believe there are some folks who may have some ideas, it'd be an interesting discussion!

Related, we had a [while back an rfc](http://lists.llvm.org/pipermail/llvm-dev/2020-August/144047.html) about whether we'd benefit from some facility for embedding data in a section in the binary - this would have been one of the motivating scenarios - if the need resurfaces, I'm sure there'll be other benefiting scenarios (there some interest on the thread, IIRC)
