### ISSUE TITLE
Demo build instructions

### ISSUE THREAD

**Issue by reedkotler** [google/ml-compiler-opt#217]
1. When I try and build the inlining demo, the instructions work until the need for "cipd". This is not a command I have
2. In the prelliminaries section, there is a typo: export WORKINGD_DIR=~ . It should be export WORKING_DIR=~

**Comment by reedkotler** [comment]
In regalloc demo, build instructions failed. 
cd src
git apply $WORKING_DIR/ml-compiler-opt/experimental/chromium-bitcode-embedding.patch

error:
git apply $WORKING_DIR/ml-compiler-opt/experimental/chromium-bitcode-embedding.patch
error: patch failed: build/config/clang/clang.gni:15
error: build/config/clang/clang.gni: patch does not apply

**Comment by mtrofin** [comment]
IIRC `cipd` comes from [here](https://github.com/google/ml-compiler-opt/blob/main/docs/inlining-demo/demo.md), specifically the link to get their source. At a point one of the packages there will add `cipd`. Attn @petrhosek in case that has changed on the Fuchsia side.

Re. the chromium patch - @boomanaiden154 , ptal? IIRC you updated the patches recently, but maybe we can specify in the demo what chromium git hash they are guaranteed to apply at?

**Comment by boomanaiden154** [comment]
The `cipd` package should come from the Fuchsia setup instructions (https://fuchsia.dev/fuchsia-src/get-started/get_fuchsia_source), specifically the part when `.jiri_root` is added to the path. I'll take a deeper look soon and probably add a note since I know other people have had trouble with it in the past. I'll try and push rebased Chromium patches too along with specifying a Chromium commit SHA (maybe working on upstreaming too).

**Comment by boomanaiden154** [comment]
Closing this issue since this should be resolved with the patches that landed recently. Let us know if you have any more issues!
