### ISSUE TITLE
Does llvm-15.04 support mlgo? What versions of tensorflow and other libraries are needed?

### ISSUE THREAD

**Issue by 18liumin** [google/ml-compiler-opt#327]

**Comment by mtrofin** [comment]
I think it doesn't. Especially because of the optional dependencies, currently the assumption is that you build from the tree at `HEAD`, i.e. it's not currently a goal to have support "out of the box". In LLVM 17, the only "out of box" support is for the interactive mode, targeting ML researchers. It lets them experiment with the passes that are currently enabled for MLGO, and with the current feature set, without needing to recompile clang.

The hope is that with EmitC support we can get more of an "out of box" experience.
