### ISSUE TITLE
`--compile_task` flag missing

### ISSUE THREAD

**Issue by TIHan** [google/ml-compiler-opt#340]
When going through the inline-demo, the `Evaluate trained policy on a corpus (Optional)` section, the command will not work because `compile_task` is missing.

```
FATAL Flags parsing error: Unknown command line flag 'compile_task'
```

**Comment by boomanaiden154** [comment]
That message seems to indicate that it's not working because the `compile_task` flag is set, but isn't actually used anywhere? The flag was removed from `generate_default_trace.py` in https://github.com/google/ml-compiler-opt/commit/2ba448732b5c9aa9ed221ac70a0009293651701e and the corresponding documentation was never updated.

I've opened #341 to fix this in the documentation, but just omitting the flag should be able to fix the immediate issue.
