### ISSUE TITLE
How MLGO collect performance data?

### ISSUE THREAD

**Issue by yingluosanqian** [google/ml-compiler-opt#412]
I would like to ask how MLGO measures the runtime of a program. In which file can I find the related code?

**Comment by mtrofin** [comment]
That's left to the specific problem. For example for regalloc, the code here uses a feature in llvm that uses PGO data and some rough estimates of load/store/copy costs to compute a per-function signal. We use an offline (without running) approach because running production programs is prohibitively time-consuming, and microbenchmarks wouldn't have feature values with distributions like in the real programs (so we wouldn't get useful models)

We're updating the offline methodology with a trace-based approach inspired by mca-daemon (see the release notes for the latest regalloc model) which works much better than the initial approach described above (which worked kind of poorly actually, we still had to run some large benchmarks in the end). The mca-daemon inspired approach doesn't have that limitation.

If your usecase is (small maybe) programs where microbenchmarks are representative, you'll probably be very successful using that instead - should be relatively straightforward to change the regalloc runner in that direction, i.e. running programs.

Hope this helps!

(Please note - a few of us are on vacation until the New Year or the first week after, so responses may be spotty)

**Comment by yingluosanqian** [comment]
This helps a lot! Really appreciate your quick response :)
