### ISSUE TITLE
Tasks assigned to LocalWorkerPool are not load balanced

### ISSUE THREAD

**Issue by Northbadge** [google/ml-compiler-opt#91]
Tracking issue, search for this issue number in code.

- `_schedule_jobs` in `local_data_collector` load balances naively, in round-robin style
- Ideally, each worker is only assigned a couple jobs at a time, and gets more upon completion of previous tasks

**Comment by mtrofin** [comment]
Kind of; the local collector isn't meant to be an efficient solution: the main constraint is the # of CPUs, and if the workload is too large, the solution is going distributed (wip). Since the overall parameters of a training setup are known - i.e. #distributed machines, #cores per machine, #modules - the naive solution may be "good enough", if the training setup is appropriately dimensioned: all compilations happen simultaneously and no module is starved.

But good to keep the issue, maybe we hit training cases when this needs addressing!

**Comment by Northbadge** [comment]
didn't isolate the specific worker no., but when I was running the validation data collector (wip)(which effectively compiles everything) it was noticeably not scheduling properly, with and without sorted-by-size modules. Might be that as Yundi pointed out in the #77, early worker numbers get more work on average since it goes 12345 12345. 

This is indeed mostly for the non-distributed case though

**Comment by mtrofin** [comment]
aa! I think the validation data collector should "look" more like generate_default_trace though

**Comment by mtrofin** [comment]
(capturing offline discussion) @Northbadge convinced me we can reasonably use the same distribution mechanism and abstraction (the workers/worker pool) for both - thanks!
